./network/netvisor/pn_log_audit_exception.py